### ISSUE TITLE
inotify is not available on win-amd64

### ISSUE THREAD

**Issue by agusmaulanaok** [Tbruno25/btc_faucet#5]
inotify is not available on win-amd64

**Comment by Tianyu9748** [comment]
Same question. Does this mean we cannot use inotify if we are using amd?

**Comment by Tbruno25** [comment]
This was made to run on Raspbian OS. If you'd like to try and use it with windows you can ignore most of these dependencies and only `pip install` the packages you see in `scanner.py` and `faucet.py`
